version: '3'

services:

    zammad:
     image: zammad/zammad
     hostname: zammadhost
     container_name: zammad
     restart: always
     ports:
      - 8080:80
     volumes:
      - zammad-data:/opt/zammad:rw
      - zammad-db:/var/lib/postgresql:rw
      
volumes:
  zammad-data:
    driver: local
  zammad-db:
    driver: local
